### ISSUE TITLE
use `pod_target_xcconfig` instead of `xcconfig` in the Podspec

### ISSUE THREAD

**Issue by AliSoftware** [xareelee/XAspect#3]
CocoaPods has migrated away from the `xcconfig` attribute in the Podspec, because it modified the User's project configuration, which can cause issues.

_For example I'm using multiple pods in my project that use that `xcconfig` attribute which modifies my User Project' settings, and they collide with each other._

That's why we introduced `pod_target_xcconfig` for cases when only modifying the Pod's own `xcconfig` is the desired behavior (which is most of the case, like here with XAspect)

See [CocoaPods's dedicated blog Post](http://blog.cocoapods.org/CocoaPods-0.38/#split-of-xcconfig) for more information.

**Comment by xareelee** [comment]
Thanks for this information. I'll fix this issue soon.

**Comment by xareelee** [comment]
This podspec issue should be fixed in **version 1.0.5**. Please try `pod update`. 

If this does not fix your issue, please let me know. Any pull request is welcome.

**Comment by AliSoftware** [comment]
I was not using XAspect directly but as part of a dependency of the XLTestLog in my project. `pod update XLTestLog` did make XAspect update to 1.0.5 and didn't warn about xcconfig conflicts anymore so I think the issue is solved :-)

Thx!

**Comment by xareelee** [comment]
Thanks for your support and hope you enjoy XLTestLog.  :-)
