### ISSUE TITLE
I'll start developing XAspect 2

### ISSUE THREAD

**Issue by xareelee** [xareelee/XAspect#4]
Hello, guys. I'll start developing the next major version of XAspect (XAspect 2.0) recently. Any idea or comment is welcome.

The major modification is programming style using XAspect 2.

Old style:

``` objc
#import <XAspect/XAspect.h>
// A aspect namespace for the aspect implementation field (mandatory).
#define AtAspect ObjectLifetime

// Create an aspect patch field for the class you want to add the aspect patches to.
#define AtAspectOfClass NSObject
@classPatchField(NSObject)

// Intercept the target objc message.
AspectPatch(-, instancetype, init)
{
    // Add your custom implementation here.
    NSLog(@"[Init]: %@", NSStringFromClass([self class]));

    // Forward the message to the source implementation.
    return XAMessageForward(init);
}

@end
#undef AtAspectOfClass
#undef AtAspect
```

New style may looks like (still working on, this is not the final version):

``` objc
#import <XAspect/XAspect.h>

// Create a namespace for the aspect patch field to do aspect-oriented programming.
// It's equivalent to the part `#define AtAspect ASPECT_NAME` in XAspect 1.
@xaspect(ObjectLifetime)

// `aspectPatch` is an object (hidden keyword) created in `@xaspect()` macro.
// Using `-className:classPatch:` to patch methods in the target class.
// It's equivalent to the part `@classPatchField(CLASS)...@end` in XAspect 1.
[aspectPatch className:@"NSObject" classPatch:^(id<XAspectClassPatch> classPatch) {

  // Create a `instead advice` 
  [classPatch instanceMethod:@selector(init) aspectPatch:^(id<XAspectMethod> method, id self) {
    // Before advice
    NSLog(@"[Init]: %@", NSStringFromClass([self class]));

    // Call the original NSInvocation.
    // You can also omit this invocation, XAspect will automatically call this
    // invocation right after this block returns.
    // If you omit this invocation, all implementation in this block is treated
    // as `before advice`.
    [method invoke];

    // After advice

    // You don't need to return any thing. All is handled by NSInvocation.
  }];

}];


@endxasepct  // close the aspect patch field
```

**Comment by ZGilbert** [comment]
Will you build a swift version?  :)

**Comment by xareelee** [comment]
@ZGilbert, I'll try to, but XAspect 2 will be only possible to support Obj-C classes in Swift because of Objective-C runtime.

Currently it is not possible to support Swift classes. There is no way to interrupt Swift messaging at runtime.

**Comment by ZGilbert** [comment]
@xareelee :)

**Comment by FKLam** [comment]
How the Aspect object's turn is？

**Comment by xareelee** [comment]
The development of XAspect 2 has been suspended for one year. 

I encountered an issue when intercepting the Obj-C messages through class hierarchy which will leads to mis-message-forwarding. Other frameworks using `_objc_msgForward`, e.g. [Aspects](https://github.com/steipete/Aspects), have the same issue too. One solution might use Assembly to rewrite a new version of `_objc_msgForward`, but it comes a high maintenance cost.

By the way, this year, I became a full-stack developer using Meteor/React/ReactNative with JavaScript, and I rarely write Objective-C. Since Swift and JavaScript become popular in iOS development, Objective-C might be outdated in a few months/years.

I'd like to develop XAspect 2, but it will still be suspended until I find a easy way to solve the issue using `_objc_msgForward` in the class hierarchy.

**Comment by JokerKin** [comment]
这是要暂停开发了吗，这个框架不在被维护。

**Comment by xareelee** [comment]
XAspect v2 has been suspended. Currently, I only fix bugs in XAspect v1.
