### ISSUE TITLE
关于分类如何引入Delegate

### ISSUE THREAD

**Issue by wujunyang** [xareelee/XAspect#5]
看到您写的开源XAspect插件，的确很棒，也解决目前我们项目中关于抽离代码的要求；今天在使用过程中碰到一个问题，假如要在我们自个创建的XAspect-GeTuiAppDelegate.m里面引入一个自定义的协议<GeTuiSdkDelegate>，这个如何在XAspect那个.m文件写呢？因为我不想把这个Delegate放在外面，如下外的代码，希望得到你的回复；再次感谢；

现在的代码：
@interface AppDelegate :jiaAppDelegate<GeTuiSdkDelegate>

@end

**Comment by xareelee** [comment]
@wujunyang ，感謝您支持 XAspect。

我沒有很理解你的問題。能否請您多敘述您的問題，以及多補充一下你的代碼？

就我對你目前提問的理解，你是想要在一個封裝 aspect 的檔案內 (XAspect-GeTuiAppDelegate.m)，加入一個 Objective-C 的 Protocol 到自己的 AppDelegate 上，是嗎？

**Comment by wujunyang** [comment]
您好  

下面这个就是生成的.h文件,像我下面这样写法是不是有问题，关于GeTuiSdkDelegate及Gtname；好像不支持？ 还有默认生成的XAspect_GTAppDelegate父类为NSObject，这个应该没有影响吧?

#import <Foundation/Foundation.h>
@interface XAspect_GTAppDelegate : NSObject<GeTuiSdkDelegate>
@property(nonatomic,copy)NSString *Gtname;
@end

**Comment by wujunyang** [comment]
您好：我重新把代码整理一下，可能你看起来会比较清楚；

问题1：第一步我创建一个XAspect-GeTuiAppDelegate.h文件，里面包含两个内容，一个是我自定义的protocol mobileProjectNoticeDelegate 还有一个是别人的GeTuiAppDelegate;现在报错在NSObject<GeTuiAppDelegate>：Expected ';'after method prototype;

#import <Foundation/Foundation.h>
#import "GeTuiSdk.h"

//处理个推事件
@protocol mobileProjectNoticeDelegate<NSObject>
-(void)receiveRemoteNotificationWithInfo:(NSDictionary *)userInfo;
-(void)gtReceiveNotificationWithOffLine:(BOOL)offLine payloadMsg:(NSString *)payloadMsg;
@end

@interface XAspect-GeTuiAppDelegate : NSObject<GeTuiAppDelegate>
@property(nonatomic,assign)id<mobileProjectNoticeDelegate> noticeDelegate;

@end




问题2：创建好的XAspect-GeTuiAppDelegate.h我是否要把它头部引入到XAspect-GeTuiAppDelegate.m里dm

**Comment by wujunyang** [comment]
#import "AppDelegate.h"
#import "XAspect.h"
#import "XAspect-GeTuiAppDelegate.h"

#define AtAspect GeTuiAppDelegate

#define AtAspectOfClass AppDelegate

如果引入头部文件XAspect-GeTuiAppDelegate.h就会出现很奇怪的报错；

**Comment by wujunyang** [comment]
如果不能在XAspect-GeTuiAppDelegate.m文件引入头文件#import "XAspect-GeTuiAppDelegate.h"   那我在.h里面的< GeTuiAppDelegate >和protocol mobileProjectNoticeDelegate又如何增加进来？

**Comment by wujunyang** [comment]
protocol mobileProjectNoticeDelegate  这个我是要开发给其它子类运用；所以得开放出来

**Comment by xareelee** [comment]
如果可以，能否直接提供產生這個問題的源代碼 (不用原本的源代碼，能在一個新的 project 內足夠重現這個問題的代碼即可)。

另外，建議你使用 GitHub 支援的 markdown 來讓代碼上色，提高可讀性：

<pre>
```objc   // 使用的上色語言
// 你的代碼塊
```
</pre>

**Comment by xareelee** [comment]
我大概猜到你的問題了

1. 你建立了一個 XAspect-GeTuiAppDelegate.m 的檔案，並使用 XAspect 來寫 AOP 代碼
2. 你希望把一個 Objective-C Protocol 引入到 XAspect-GeTuiAppDelegate.m 內的某個類別上

首先，你對 XAspect 有很大的誤解。XAspect 是利用大量的 C Macros 來對「目標類別」建立一個「子類別 (subclass)」來處理所有需要 method injection 和 method swizzling 的事前準備。

例如：

```objc
#define AtAspect GTAppDelegate
#define AtAspectOfClass jiaAppDelegate
@classPatchField(jiaAppDelegate)

...

@end
#undef AtAspectOfClass
#undef AtAspect
```

實際上就是 `AtAspect` 和 `AtAspectOfClass` 這兩個 Macro 的定義來合成一個類別繼承宣告：

```objc
// class name: _AtAspect_ ## `AtAspectOfClass` ## _OfClass_ ## `AtAspect` ## _
@interface _AtAspect_GTAppDelegate_OfClass_jiaAppDelegate_ : jiaAppDelegate
...
@end
```

在程式 Loading 時期 (執行 `main()` 之前)，會自動將 XAspect 產生的類別，進行 method injection 和 method swizzling (也就是用 `AspectPatch()` 寫的 method patch)。

因此，你以下這行就變得有問題了：

```objc
@interface XAspect_GTAppDelegate : NSObject< GeTuiSdkDelegate >
...
@end
```

`XAspect_GTAppDelegate` 這個類別的用途是什麼？你是否有寫 `@implementation` 的實作？

在 XAspect 下，`XAspect-GeTuiAppDelegate.m` 裡面並**不會**產生一個 `XAspect-GeTuiAppDelegate` 類別。**檔案名稱**跟**類別名稱**，並非要相同，也並非一定要有關連。

因此針對 XAspect-GeTuiAppDelegate.m 創見一個對應的 XAspect-GeTuiAppDelegate.h 並宣告一個 `XAspect-GeTuiAppDelegate` class 是沒有意義的，因為你還是需要實踐它 (`@implmentation`)；但是這也看起來不像是你要的。

你的問題看起來這只是單純的 Objective-C 的 Category/Protocol，你需要的只是對原本的目標類別藉由 Category 來進行擴展、加入 Protocol。
